### ISSUE TITLE
Fails to compile on latest nightly

### ISSUE THREAD

**Issue by royalmustard** [rust-lang/packed_simd#345] opened 2022-05-31 18:02 UTC
`error: expected one of `!` or `::`, found keyword `mod`
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/packed_simd_2-0.3.7/src/lib.rs:347:7
    |
347 | crate mod llvm {
    |       ^^^ expected one of `!` or `::`

error: could not compile `packed_simd_2` due to previous error`

nightly-x86_64-unknown-linux-gnu (default)
rustc 1.63.0-nightly (c35035cef 2022-05-30)

**Comment by thomcc** [comment] 2022-05-31 18:03
Dupe of https://github.com/rust-lang/packed_simd/issues/343. That just had the fix land a few minutes ago, presumably someone will cut a release soon.

**Closed by thomcc** 2022-05-31 18:03 UTC

**Comment by evolvedmicrobe** [comment] 2022-05-31 20:55
+1 for a release soon
